name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # We can expand this later to include: macos-latest, windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup Mono/F#
      if: matrix.os != 'windows-latest'  # Mono not needed on Windows
      run: |
        sudo apt-get update
        sudo apt-get install -y fsharp

    - name: Make scripts executable
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x fsi
        chmod +x test_fsi.fsx

    - name: Run tests
      run: ./test_fsi.fsx
